### PR TITLE
feat: add options always_show_by_pattern

### PR DESCRIPTION
**Pull request by PumpedSardines**
Implementing the option requested in the issue #1255. Tested on my neovim setup and seems to work.

I've worked very little on neovim plugins so if i've missed to add something please point it out!

### CODE REVIEW

**Comment by PumpedSardines** [comment]
@cseickel 

Don't want to tag people, but wondering if this could get reviewed?

**Review by cseickel — APPROVED** [review]
Sorry for forgetting about this. LGTM.

@pysan3 Any comments?

**Comment by pysan3** [comment]
My bad, I forgot about this.

**Comment by pysan3** [comment]
I'll release a new version soon as well ;)

**Pull request merged**
