### PR TITLE
feat: disable signcolumn by default

### PR DESCRIPTION
**Pull request by danilshvalov**
Hi! I think it would be better if `signcolumn` was disabled by default.

<details>
<summary>Before</summary>

before
</details>

<details>
<summary>After</summary>

after
</details>

### CODE REVIEW

**Comment by cseickel** [comment]
I'm not sure. Either way a person can override whatever the default is, but is it better to explicitly set it to off by default, or do nothing and assume the user's global default is what they expect?

I personally want the sign column on in all of my windows, because I think it looks wrong without some kind of margin.

We get a few people asking how to disable it, but not that many. The question is: 

1. Are there a lot of people that want to change it, but they quietly have figured it out on their own?
2. Or do most people actually like it the way it is?

Another thing, your screen shot has an extra space on the left hand side that I don't have. I wonder why that is? Here is what mine looks like with the sign column on:
image

and with the sign column off:
image

**Comment by MunifTanjim** [comment]
> but is it better to explicitly set it to off by default, or do nothing and assume the user's global default is what they expect?

I think if the signcolumn is not being used, it should be hidden by default. It shouldn't just be used for padding. There is already an option for padding in `indent` component.

**Comment by cseickel** [comment]
> But the default value is `1`.

Well that does change things. I wonder why no one else has ever said anything about the extra padding? I really need to clean up that config of mine, I use it for so many test cases it ends up full of junk...

> I think if the signcolumn is not being used, it should be hidden by default. It shouldn't just be used for padding. There is already an option for padding in indent component.

OK, there's one vote to remove it.

**Review by cseickel — APPROVED** [review]

**Comment by akinsho** [comment]
Only commenting on here since I think you were wondering what users in general thought, 
> Are there a lot of people that want to change it, but they quietly have figured it out on their own?

I was very much in this camp, the spacing was duplicated for me, I guess due to the default padding + the signcolumn, so I had it disabled locally. Glad it's now the default

**Pull request merged**
