### PR TITLE
889 windows path escape

### PR DESCRIPTION
**Pull request by miversen33**
Addresses #889 
Tagging @SilverMira @treturner for testing

Tagging @cseickel and @pysan3 for review. The change is pretty small, thanks to @SilverMira for the little code snippet :) Basically just checking to see if we are on windows and if we are, doing a glob substitute on the path to ensure that anything that isn't escaped **is** escaped now.

### CODE REVIEW

**Review by treturner — COMMENTED** [review]
That code snippet worked for me. Can open the file from neotree and treesitter. Thanks @miversen33 and @SilverMira

**Comment by pysan3** [comment]
Hi @miversen33 

This is just my preference but we have `windowize_path` function around L900 which is exactly the reverse of `escape_path` so I think it should be written next to it?

Also, we already have `M.is_windows` defined at around L690 and I think we should use that instead of `has(win32)`? I'm not sure tho.

**Comment by miversen33** [comment]
> Hi @miversen33 
> 
> This is just my preference but we have `windowize_path` function around L900 which is exactly the reverse of `escape_path` so I think it should be written next to it?
> 
> Also, we already have `M.is_windows` defined at around L690 and I think we should use that instead of `has(win32)`? I'm not sure tho. 

I have no issue in updating the position and using that function (I didn't even think to see if that existed lol). I'll update the PR with these requests

**Comment by miversen33** [comment]
I've made the requested changes. Lemme know if there are any other requests :)

**Review by SilverMira — APPROVED** [review]
Yup, that does fix it for neo-tree

**Review by cseickel — APPROVED** [review]

**Pull request merged**
