### PR TITLE
feat(command): add source `last` refers to the last executed source

### PR DESCRIPTION
**Pull request by ofseed**
Implement #775 , add a source option `last` to allow users to open the last source used.

### CODE REVIEW

**Comment by ofseed** [comment]
Furthermore, considering the `:Neotree` command without a specific source is heavily used when interacting with users and most users don't truly trust the default when they need to open a specific source, I personally recommend setting the`default_source` to `last` in `neo-tree.defaults`.

**Review by cseickel — COMMENTED** [review]
This is a good idea, but it's not quite complete because it ignores the position that the `last` source was opened in. I don't always use the same position so it's not enough for me to just set a default for every source, and when I use `last` I expect it to be the last **source** and the last **position**.

**Comment by cseickel** [comment]
> Furthermore, considering the `:Neotree` command without a specific source is heavily used when interacting with users and most users don't truly trust the default when they need to open a specific source, I personally recommend setting the`default_source` to `last` in `neo-tree.defaults`.

I don't think you have any way of knowing that, you are just speaking about your own usage here and projecting that on others. 90% of the time I use a mapping and not the command. When I just use `:Neotree` without specifying a source, I expect it to be the "filesystem" source because that is the one I use more often. Also, based on my interactions with users to date I would say that the vast majority of users primarily use the "filesystem" source, so it makes sense that this would be the default.

**Comment by ofseed** [comment]
Of course, this is merely a minor suggestion for the design. Since it could disrupt existing user configurations, I'm not implementing these thoughts in the current PR.

But honestly, I think this design is a little weird. Considering neo-tree could switch between different sources in the same window, some users might be very eager to leverage this feature, and there is a situation:

I opened a neo-tree filesystem window by `Neotree toggle` (no matter with a keymap or enter the command directly), and after a while, I switch to another source like the buffer source. Finally, I want to close the existing neo-tree window by `Neotree toggle` because I think it would do that, but the result is I switch the current window to the filesystem window rather than close it.

What I want to demonstrate is when you toggle, you'd better know what you are toggle, rather than take advantage of the default value. If you assign a key to the Neotree toggle filesystem, it becomes clear that this key is solely for toggling the filesystem, regardless of the current source.

In fact, this PR also solves the previous problem. Because switching to another source would call `execute` again, when you use `Neotree toggle last`, no matter what source you switched after that, `Neotree toggle last` will close this window.

But as I mentioned before, I would not implement it in this PR, it is just a suggestion.

**Comment by ofseed** [comment]
I discovered that implementing this feature might not require extra work. because when I execute Neotree toggle <source> without specifying an explicit position, it defaults to the last position where this source was opened.

So, in essence, Neotree toggle is equivalent to Neotree toggle position=last. The only requirement is to implement source=last, which has been accomplished in this PR.

**Comment by cseickel** [comment]
> I discovered that implementing this feature might not require extra work. because when I execute Neotree toggle without specifying an explicit position, it defaults to the last position where this source was opened.

It does do that most of the time, but not always. It does not work for `position="current"`. If you use the `current` position, it will toggle the default position of the sidebar version instead.

**Comment by ofseed** [comment]
Completed, the position will be last if it is not specified now.

**Review by cseickel — APPROVED** [review]
Works perfectly!

**Pull request merged**
