### PR TITLE
Update doc, highlight and indent.

### PR DESCRIPTION
**Pull request by ur4ltz**
- feat(document_symbols): added follow_cursor(#880)
- fix: set correct winid when window.position = current (#874)
- fix: declare `bufnr` as local to avoid polluting global namespace (#883)
- fix!: use correct conversion between tabid and tabnr when tracking cwd (#842)
- Update doc

### CODE REVIEW

**Review by miversen33 — DISMISSED** [review]
LGTM

**Comment by cseickel** [comment]
Thanks for this. There are two issues:

1. PRs need to target the `main` branch, I just changed that for you.
2. There is a merge conflict, can you rebase/merge the current main branch?

**Comment by ur4ltz** [comment]
I'm sorry, I'm not a big git expert, I did everything I could.

**Review by cseickel — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
