### PR TITLE
fix: auto_expand_width gets caught in infinite loop and hangs neovim (#624)

### PR DESCRIPTION
**Pull request by pysan3**
Should fix https://github.com/nvim-neo-tree/neo-tree.nvim/issues/624.

For more info and discussion, please read the above issue.

### CODE REVIEW

**Review by cseickel — APPROVED** [review]
Works great for me!

**Comment by cseickel** [comment]
Actually, this is still not quite right. I just got into a situation where I could not scroll vertically in a neo-tree window because every movement caused a re-render and put me back to the top of the window.

I disabled the feature in my own config for now. I think this can use some more work.

**Comment by pysan3** [comment]
@cseickel Thanks for testting.

Could you give me a minimal way to reproduce your issue?

I really cannot have the same behavior with my setup and I have no issues whatsoever.

And could you test what happens when `auto_expand_width = false` and toggle it on with keybind after opening neo-tree.

The rendering should only happen on what was already implementing before adding this feature or when the rendering text length exceeds the width of the window.
I could not think of a reason why this feature interferes with scrolling.

Thanks in advance.

**Comment by cseickel** [comment]
@pysan3 I think this is the core issue: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/4c3d9d55591ffad68518a77447f2ed141913685f/lua/neo-tree/ui/renderer.lua#L946

That creates an infinite loop of renders whenever the auto_expand code is actually triggered.

I ended up rewriting the logic to be more direct and ensure there is only one extra render. I'm also making it something that can be reused for position = `current` and `float`. I'm not quite done with that but the code is in #629.

**Comment by pysan3** [comment]
@cseickel Thank you so so much!!

Your rewrite works like a charm!

**Pull request merged**
